Temporary test.

diff --git a/.github/workflows/config.yml b/.github/workflows/config.yml
--- a/.github/workflows/config.yml
+++ b/.github/workflows/config.yml
@@ -8,56 +8,56 @@ on:
   workflow_dispatch:
 
 jobs:
-  run-ruleset-tests:
-    runs-on: ubuntu-latest
-    container:
-      image: docker://nrel/openstudio:3.8.0
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          ref: ${{ github.head_ref }}
+  # run-ruleset-tests:
+    # runs-on: ubuntu-latest
+    # container:
+      # image: docker://nrel/openstudio:3.8.0
+    # steps:
+      # - uses: actions/checkout@v4
+        # with:
+          # ref: ${{ github.head_ref }}
 
-      - name: Install software
-        run: |
-          rm -f Gemfile.lock && bundle install
-          export DEBIAN_FRONTEND=noninteractive
-          sudo apt update
-          sudo -E apt-get install -y wget unzip python3-sphinx-rtd-theme
+      # - name: Install software
+        # run: |
+          # rm -f Gemfile.lock && bundle install
+          # export DEBIAN_FRONTEND=noninteractive
+          # sudo apt update
+          # sudo -E apt-get install -y wget unzip python3-sphinx-rtd-theme
 
-      - name: Check HPXMLs
-        shell: bash
-        run: |
-          echo "Regenerating HPXML files..."
-          openstudio tasks.rb update_measures
-          echo "Checking for HPXML differences..."
-          git config --global --add safe.directory $(realpath .)
-          git diff --exit-code --ignore-cr-at-eol workflow/*.xml
+      # - name: Check HPXMLs
+        # shell: bash
+        # run: |
+          # echo "Regenerating HPXML files..."
+          # openstudio tasks.rb update_measures
+          # echo "Checking for HPXML differences..."
+          # git config --global --add safe.directory $(realpath .)
+          # git diff --exit-code --ignore-cr-at-eol workflow/*.xml
 
-      - name: Run ruleset tests
-        run: |
-          bundle exec rake test_rulesets
+      # - name: Run ruleset tests
+        # run: |
+          # bundle exec rake test_rulesets
 
-      - name: Store code coverage
-        uses: actions/upload-artifact@v4
-        with:
-          path: coverage
-          name: coverage
+      # - name: Store code coverage
+        # uses: actions/upload-artifact@v4
+        # with:
+          # path: coverage
+          # name: coverage
 
-      - name: Build documentation
-        run: |
-          cd docs
-          make html SPHINXOPTS="-W --keep-going -n"
+      # - name: Build documentation
+        # run: |
+          # cd docs
+          # make html SPHINXOPTS="-W --keep-going -n"
 
-      - name: Check documentation
-        run: |
-          echo "Checking for misaligned documentation footnotes..."
-          for RST_FILE in docs/source/*.rst; do NUM_REFS=$(grep -F -o "[#]_" $RST_FILE | wc -l); NUM_FOOTNOTES=$(grep -F -o ".. [#]" $RST_FILE | wc -l); if [ $NUM_REFS != $NUM_FOOTNOTES ]; then echo "ERROR: Number of footnote references doesn't match number of footnotes in $RST_FILE." && exit 1; fi done
+      # - name: Check documentation
+        # run: |
+          # echo "Checking for misaligned documentation footnotes..."
+          # for RST_FILE in docs/source/*.rst; do NUM_REFS=$(grep -F -o "[#]_" $RST_FILE | wc -l); NUM_FOOTNOTES=$(grep -F -o ".. [#]" $RST_FILE | wc -l); if [ $NUM_REFS != $NUM_FOOTNOTES ]; then echo "ERROR: Number of footnote references doesn't match number of footnotes in $RST_FILE." && exit 1; fi done
 
-      - name: Save Docs
-        uses: actions/upload-artifact@v4
-        with:
-          name: documentation
-          path: docs/_build/html/
+      # - name: Save Docs
+        # uses: actions/upload-artifact@v4
+        # with:
+          # name: documentation
+          # path: docs/_build/html/
 
   run-sample-files1-tests:
     runs-on: ubuntu-latest
